project_id = "yuabwnhulzhnoyvnvqrw"

[functions.join-event]
verify_jwt = false

[functions.csv-import]
verify_jwt = false

[functions.attendance]
verify_jwt = false

[functions.org-management]
verify_jwt = false

[functions.moderation]
verify_jwt = false

[functions.admin-safety]
verify_jwt = false
